name: Elvis de Souza
#description: "Mestrando em linguística computacional, professor de inglês e desenvolvedor freelancer"
description: Mestrando em Estudos da Linguagem, membro do grupo de pesquisa em Linguística Computacional, Corpus e Humanidades Digitais
meta_description: "Linguagem e tecnologia"

exclude: ['chatbot/flask/']

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://alvelvis.github.io"
google_analytics: "G-12ZKTMN0RJ"
plugins: [jekyll-paginate]

about: 'sobre'
english: 'aprenda-ingles'
freela: 'freela'

picture: '/assets/images/profile3.jpg'

authordesc: "Escrevo sobre linguagem, robôs, e sobre como robôs aprendem linguagem."
authordescen: "I write about language, robots, and how robots learn language."
authordesc2: Pós-graduando em Linguística Computacional no PPGEL/PUC-Rio. Entendo um pouco de linguagem, de robôs, e de como robôs aprendem linguagem.
profdesc: Mestrando do Programa de Pós-Graduação em Estudos da Linguagem da Pontifícia Universidade Católica do Rio de Janeiro (PPGEL/PUC-Rio) e bacharel em Letras (Português/Inglês) pela PUC-Rio. Membro do grupo de pesquisa em Linguística Computacional, Corpus e Humanidades Digitais [(ComCorHd/PUC-Rio)](http://comcorhd.letras.puc-rio.br) desde 2018.

generalskills: "
\n- Capacidade de liderança e de trabalho em equipe
\n- Inglês fluente, excelente escrita e experiência com pesquisa no âmbito acadêmico
\n- Comunicação eficiente e não violenta
"
specificskills: "
\n- Conhecimento de diversas linguagens de programação
\n- Desenvolvimento back-end (Python, Flask/Django) e front-end (Web e PWA com JavaScript, Pascal/Lazarus)
\n- Conhecimento de infraestrutura web (Apache), aprendizado de máquina, Linux e Git
"

#\n- Usuário experiente e incansável das ferramentas de busca on-line

portfolio: "
\n- Tronco
\n\t- Aplicativo de bloco de notas e tarefas multiplataforma
\n\t- Site: [tronco.ga](https://tronco.ga)
\n\t- Código-fonte: [github.com/alvelvis/Tronco](https://github.com/alvelvis/Tronco)
\n- Interrogatório
\n\t- Ambiente on-line de busca e revisão de corpora anotados
\n\t- Site: [interrogatorio.comcorhd.ga](http://interrogatorio.comcorhd.ga)
\n\t- Código-fonte: [github.com/alvelvis/Interrogat-rio](https://github.com/alvelvis/Interrogat-rio)
\n- AraSAS
\n\t- Anotador semântico de textos em árabe (versão árabe do [USAS - UCREL Semantic Analysis System](http://ucrel.lancs.ac.uk/usas/))
\n\t- Site: [arasas.herokuapp.com](http://arasas.herokuapp.com/)
\n\t- Código-fonte: privado. O back-end foi desenvolvido em Python utilizando o framework Flask.
"
    
# Details for the RSS feed generator
url: "https://alvelvis.github.io"
author: "Elvis de Souza"

# Disqus config
disqus-shortname: ""
