name: Elvis de Souza
#description: "Mestrando em linguística computacional, professor de inglês e desenvolvedor freelancer"
description: Mestre em Estudos da Linguagem e Pesquisador em Inteligência Artificial e Processamento de Linguagem Natural
meta_description: "Linguagem e tecnologia"

exclude: ['chatbot/flask/']

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://souelvis.dev"
google_analytics: "G-12ZKTMN0RJ"
plugins: [jekyll-paginate]

about: 'sobre'
english: 'aprenda-ingles'
freela: 'freela'

picture: '/assets/images/profile.png'

authordesc: "Escrevo sobre humanos, robôs, linguagem, e sobre como humanos e robôs aprendem linguagem."
authordescen: "I write about humans, robots, language, and how humans and robots learn language."
profdesc: Pesquisador em projetos no campo do Processamento de Linguagem Natural (NLP) e Inteligência Artificial no Laboratório de Inteligência Computacional Aplicada da PUC-Rio (ICA/PUC-Rio). Doutorando em Ciências de Computação e Matemática Computacional (ICMC/USP), mestre em Estudos da Linguagem (PPGEL/PUC-Rio) e bacharel em Letras (PUC-Rio). Interessado em Processamento de Linguagem Natural, Linguística Computacional, Humanidades Digitais e estudos linguísticos descritivos baseados em corpus.

generalskills: "
\n- Capacidade de liderança e de trabalho em equipe
\n- Inglês fluente, excelente escrita e experiência com pesquisa no âmbito acadêmico
\n- Comunicação eficiente e não violenta
"
specificskills: "
\n- Conhecimento de diversas linguagens de programação
\n- Desenvolvimento back-end (Python, Flask/Django) e front-end (Web e PWA com JavaScript, Pascal/Lazarus)
\n- Conhecimento de infraestrutura web (Apache), aprendizado de máquina, Linux e Git
"

#\n- Usuário experiente e incansável das ferramentas de busca on-line

portfolio: "
\n- AraSAS
\n\t- Anotador semântico de textos em árabe (versão árabe do [USAS - UCREL Semantic Analysis System](http://ucrel.lancs.ac.uk/usas/))
\n\t- Site: [arasas.souelvis.dev](http://arasas.souelvis.dev/)
\n\t- Código-fonte: [github.com/UCREL/AraSAS](https://github.com/UCREL/AraSAS). O back-end foi desenvolvido em Python e o aplicativo utiliza o framework Flask.
\n- Buscador de frases em corpora anotados no formato CoNLL-U
\n\t- Interface web para busca de frases em corpora anotados no formato CoNLL-U. Suporta buscas de dependências complexas no padrão Grew e visualização de árvores sintáticas e grafos enriquecidos (EUD).
\n\t- Site: [conllu.souelvis.dev](https://conllu.souelvis.dev/)
\n\t- Código-fonte: [github.com/alvelvis/conllu-quick-search](https://github.com/alvelvis/conllu-quick-search)
\n- Anotador de Dependências Sintáticas Enriquecidas (EUD) para o Português
\n\t- Interface web para anotação de dependências sintáticas enriquecidas (EUD). O anotador utiliza um conjunto de regras adaptadas do programa [Grew](http://grew.fr/) para o [português brasileiro](https://sol.sbc.org.br/index.php/stil/article/view/31134).
\n\t- Site: [eud-portugues.souelvis.dev](https://eud-portugues.souelvis.dev/)
\n\t- Código-fonte: [github.com/alvelvis/eud-portugues](https://github.com/alvelvis/eud-portugues)
\n- Visualizador de Grafo Enriquecido (EUD)
\n\t- Interface web para visualização altamente customizável de frases no formato CoNLL-U com anotação de dependências sintáticas enriquecidas (EUD).
\n\t- Site: [souelvis.dev/enhanced-graph-visualiser/visualise.html](https://souelvis.dev/enhanced-graph-visualiser/visualise.html)
\n\t- Código-fonte: [github.com/alvelvis/enhanced-graph-visualiser](https://github.com/alvelvis/enhanced-graph-visualiser)
\n- UD Validate
\n\t- Interface web para validação de frases anotadas no formato [Universal Dependencies](https://universaldependencies.org/)
\n\t- Site: [ud-validate.souelvis.dev](https://ud-validate.souelvis.dev/)
\n\t- Código-fonte: [github.com/alvelvis/ud-validate](https://github.com/alvelvis/ud-validate)
\n- Interrogatório
\n\t- Ambiente on-line de busca e revisão de corpora anotados no formato [Universal Dependencies](https://universaldependencies.org/)
\n\t- Código-fonte: [github.com/alvelvis/Interrogat-rio](https://github.com/alvelvis/Interrogat-rio)
\n- Petrolês
\n\t- Recursos do projeto Petrolês, um repositório de artefatos de Processamento de Linguagem Natural especializados no domínio de petróleo em Português
\n\t- Site: [petroles.puc-rio.ai](https://petroles.puc-rio.ai/)
\n- Tronco
\n\t- Aplicativo de bloco de notas e tarefas multiplataforma
\n\t- Código-fonte: [github.com/alvelvis/Tronco](https://github.com/alvelvis/Tronco)
"
    
# Details for the RSS feed generator
url: "https://souelvis.dev"
author: "Elvis de Souza"

# Disqus config
disqus-shortname: ""
