name: elvis
description: Tecnologia e linguagem
meta_description: "Tecnologia e linguagem"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://alvelvis.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://alvelvis.github.io"
author: "Elvis de Souza"

# Disqus config
disqus-shortname: ""
